/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-secondary-container": "#0f172a",
        "surface-dim": "#f8fafc",
        "tertiary-fixed": "#e2e8f0",
        "on-tertiary": "#ffffff",
        "surface-bright": "#ffffff",
        "tertiary-container": "#f1f5f9",
        "inverse-primary": "#f8fafc",
        "outline": "#cbd5e1",
        "tertiary-fixed-dim": "#cbd5e1",
        "surface-variant": "#f1f5f9",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#334155",
        "secondary-fixed-dim": "#e2e8f0",
        "surface-container-high": "#f1f5f9",
        "surface-container": "#f8fafc",
        "brand-gold": "#eab308",
        "inverse-on-surface": "#f1f5f9",
        "on-surface": "#0f172a",
        "primary-fixed-dim": "#cbd5e1",
        "on-primary-container": "#0f172a",
        "tertiary": "#475569",
        "on-primary-fixed-variant": "#334155",
        "on-primary-fixed": "#0f172a",
        "outline-variant": "#e2e8f0",
        "error-container": "#fee2e2",
        "surface-tint": "#0f172a",
        "primary-container": "#e2e8f0",
        "on-error-container": "#7f1d1d",
        "on-error": "#ffffff",
        "surface": "#ffffff",
        "error": "#ef4444",
        "inverse-surface": "#1e293b",
        "surface-container-low": "#ffffff",
        "primary-fixed": "#e2e8f0",
        "on-secondary": "#ffffff",
        "primary": "#0f172a",
        "on-tertiary-fixed-variant": "#334155",
        "on-secondary-fixed": "#0f172a",
        "surface-container-highest": "#e2e8f0",
        "secondary-container": "#f1f5f9",
        "on-tertiary-container": "#0f172a",
        "on-tertiary-fixed": "#0f172a",
        "secondary": "#334155",
        "on-primary": "#ffffff",
        "background": "#ffffff",
        "on-surface-variant": "#475569",
        "on-background": "#0f172a",
        "secondary-fixed": "#f8fafc"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "margin-desktop": "32px",
        "unit": "8px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "container-max": "1280px"
      },
      "fontFamily": {
        "label-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "display-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg": ["Inter"],
        "label-sm": ["Inter"],
        "headline-md": ["Inter"]
      },
      "fontSize": {
        "label-md": ["14px", {"lineHeight": "20px", "fontWeight": "500"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
