services:
  # 1. The Database Engine
  db:
    image: postgres:15-alpine
    container_name: ecommerce-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # 2. Database visual manager
  pgadmin:
    image: dpage/pgadmin4
    container_name: ecommerce_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
    depends_on:
      - db

  # 3. Node.js API Backend
  backend:
    build: ./backend
    container_name: ecommerce_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db

  # 4. React Frontend User Interface
  frontend:
    build: ./frontend
    container_name: ecommerce_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  # 5. Nginx Reverse Proxy / Router
  nginx:
    build: ./nginx
    container_name: ecommerce_proxy
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  pgdata:
